### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by julienschmidt** [rs/xmux#2]
I just discovered your fork. Great work so far!

Unfortunately there is a license issue. Like the Go source, HttpRouter is licensed under the new BSD (aka BSD 3-Clause) license. While it is also a permissive license, it can NOT be re-licensed to MIT, as it requires to preserve the redistribution conditions.

![compatibility chart](https://upload.wikimedia.org/wikipedia/commons/1/1d/Floss-license-slide-image.png)

**Comment by rs** [comment]
Thanks for pointing that out.
